FROM centos
RUN yum upgrade -y && yum -y install bash git curl ca-certificates java-1.8.0-openjdk-devel mariadb postgresql && yum clean all && rm -rf /var/cache/yum
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0
COPY tomcat /usr/local/tomcat
RUN sed -i '/${tomcat.ajpport}/s/<!-- /</;/${tomcat.ajpport}/s/ -->/>/' /usr/local/tomcat/conf/server.xml
RUN chmod +x /usr/local/tomcat/bin/*.sh /usr/local/tomcat/run.sh
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract
EXPOSE 8080 8443 8009 8005 8000
CMD cd /usr/local/tomcat; ./run.sh -t
