FROM centos:7
ARG date
LABEL org.label-schema.name="simplicite" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server" \
      org.opencontainers.image.title="Simplicite server" \
      org.opencontainers.image.description="Simplicite server" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"
RUN yum upgrade -y && \
    yum clean all && \
    yum install -y epel-release && \
    yum -y install bash git curl ca-certificates libjpeg java-latest-openjdk-devel mariadb postgresql && \
    yum clean all && \
    rm -rf /var/cache/yum
#RUN yum install -y yum-utils && package-cleanup --oldkernels --count=1
ENV LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JAVA_HOME=/usr/lib/jvm/java
COPY run.sh /usr/local/bin/run
COPY tomcat /usr/local/tomcat
RUN chmod +x /usr/local/bin/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract
EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/bin/run" ]
