FROM centos:8

ARG date

LABEL org.label-schema.name="simplicite-server-centos8-base" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-base" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / Base" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / Base" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="${date}"

RUN dnf upgrade -y && \
    dnf clean all && \
    dnf install -y epel-release && \
    dnf install -y bash openssh git curl wget zip unzip ca-certificates libjpeg mariadb postgresql && \
    dnf clean all && \
    rpm -i http://mirrors.ircam.fr/pub/dag/redhat/el7/en/x86_64/rpmforge/RPMS/uni2ascii-4.18-1.el7.rf.x86_64.rpm
ENV CENTOS=8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract && \
    chmod +x /usr/local/tomcat/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh

WORKDIR /usr/local/tomcat

EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
