FROM centos:7

ARG date

LABEL org.label-schema.name="simplicite-server-centos7-base" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos7-base" \
      org.opencontainers.image.title="Simplicite server / CentOS 7 / Base" \
      org.opencontainers.image.description="Simplicite server / CentOS 7 / Base" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=centos7 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN rm -f /usr/local/tomcat/bin/*.bat /usr/local/tomcat/bin/*.exe /usr/local/tomcat/bin/*.dll && \
    yum install -y dnf && yum clean all && rm -rf /var/cache/yum && \
    dnf upgrade -y && \
    dnf install -y epel-release && \
    dnf install -y bash openssh-clients openssl git curl wget zip unzip ca-certificates libjpeg fontconfig mariadb postgresql && \
    dnf clean all && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    /bin/update-ca-trust extract && \
    chmod +x /usr/local/tomcat/run && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
