FROM openjdk:15-alpine

ARG date
LABEL org.label-schema.name="simplicite-server-alpine" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-alpine" \
      org.opencontainers.image.title="Simplicite server / Alpine" \
      org.opencontainers.image.description="Simplicite server / Alpine" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"

RUN apk update && \
    apk upgrade && \
    apk add --update bash git curl wget ca-certificates libjpeg mysql-client postgresql-client && \
    rm -rf /var/cache/apk/*
ENV LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8
# JAVA_HOME is defined by default

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates && \
    groupadd tomcat && useradd -g tomcat tomcat && \
    chmod +x /usr/local/tomcat/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh && \
    chown -R tomcat:tomcat /usr/local/tomcat

USER tomcat
WORKDIR /usr/local/tomcat

EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/tomcat/run" ]
