ARG tag=latest
FROM simplicite/platform:$tag

# Install the SQLServer client 
ENV ACCEPT_EULA=Y
ADD https://packages.microsoft.com/config/rhel/7/prod.repo /etc/yum.repos.d/msprod.repo
RUN yum install -y mssql-tools unixODBC-devel && yum clean all
ENV PATH="/opt/mssql-tools/bin:${PATH}"
