FROM alpine:latest

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-alpine-temurin-jre-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-alpine-temurin-jre-${jvm}" \
      org.opencontainers.image.title="Simplicite server / Alpine / Temurin OpenJDK JRE ${jvm}" \
      org.opencontainers.image.description="Simplicite server / Alpine / Temurin OpenJDK JRE ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="$date"

ENV DOCKER=alpine LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8 JAVA_HOME=/usr/local/jre LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY jre-${jvm}-alpine /usr/local/jre
COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /usr/local/share/ca-certificates/
RUN apk update && apk upgrade && \
    apk add --update bash openssh-client openssl git curl wget zip unzip ca-certificates libjpeg fontconfig ttf-dejavu mysql-client postgresql-client && \
    rm -rf /var/cache/apk/* && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    update-ca-certificates && \
    chmod +x /usr/local/tomcat/run && \
    addgroup -g 2000 simplicite && adduser -D -G simplicite -u 2000 simplicite

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
