FROM simplicite/server:centos8-base

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-centos8-openjdk-${jvm}-jre" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-openjdk-${jvm}-jre" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / OpenJDK ${jvm} (JRE)" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / OpenJDK ${jvm} (JRE)" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

RUN dnf install -y java-${jvm}-openjdk && dnf clean all
ENV JAVA_HOME=/usr/lib/jvm/jre
