ARG reg=registry.simplicite.io
ARG tag
FROM ${reg}/server:$tag

ARG date
ARG branch
ARG version
ARG patchlevel
ARG revision
ARG commitid
ARG template

LABEL org.label-schema.name="simplicite-platform-$version" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="https://docs.simplicite.io/license.md" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-platform-$version" \
      org.opencontainers.image.title="Simplicite platform $version" \
      org.opencontainers.image.description="Simplicite platform $version" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.url="https://www.simplicite.io" \
      org.opencontainers.image.version="$version.$patchlevel.$revision" \
      org.opencontainers.image.revision="$commitid" \
      org.opencontainers.image.documentation="https://docs.simplicite.io" \
      org.opencontainers.image.licenses="https://docs.simplicite.io/license.md" \
      org.opencontainers.image.created="$date"

# TODO: HEALTHCHECK --interval=60s --timeout=3s --start-period=300s CMD curl --fail http://localhost:8080/ping || exit 1

ARG destpath=tomcat
ADD --chown=simplicite:simplicite $template/app /usr/local/$destpath/webapps/ROOT
