ARG jvm
ARG date

FROM eclipse-temurin:${jvm}

LABEL org.label-schema.name="simplicite-server-adoptium-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-adoptium-${jvm}" \
      org.opencontainers.image.title="Simplicite server / Adoptium (${jvm})" \
      org.opencontainers.image.description="Simplicite server / Adoptium (${jvm})" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="$date"

ENV DOCKER=adoptium LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8
# JAVA_HOME is defined by default

COPY *.crt /usr/local/share/ca-certificates/
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y apt-utils && \
    apt-get install -y bash openssh-client openssl git curl wget zip unzip ca-certificates libjpeg-dev mysql-client postgresql-client && \
    apt-get clean && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    update-ca-certificates && \
    addgroup --gid 2000 simplicite && adduser --disabled-password --gecos "" --uid 2000 --gid 2000 simplicite

COPY --chown=simplicite:simplicite tomcat /usr/local/tomcat
COPY --chown=simplicite:simplicite run.sh /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/tomcat/run" ]
