ARG variant
FROM simplicite/server:centos8${variant}-jre

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-centos8-openjdk-${jvm}-jdk" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-openjdk-${jvm}-jdk" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / OpenJDK = ${jvm} (JDK)" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / OpenJDK = ${jvm} (JDK)" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="${date}"

RUN dnf install -y java-${jvm}-openjdk-devel && dnf clean all
ENV JAVA_HOME=/usr/lib/jvm/java

EXPOSE 8000
