ARG jvm
FROM openjdk:${jvm}-alpine

ARG date
LABEL org.label-schema.name="simplicite-server-openjdk-${jvm}-alpine" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-${jvm}-alpine" \
      org.opencontainers.image.title="Simplicite server / OpenJDK ${jvm} Alpine" \
      org.opencontainers.image.description="Simplicite server / OpenJDK ${jvm} Alpine" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"

ENV DOCKER=openjdk-alpine LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
RUN mkdir /root/.ssh && chmod 700 /root/.ssh && chmod +x /usr/local/tomcat/run

WORKDIR /usr/local/tomcat

EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
