ARG tag
FROM simplicite/server:$tag

ARG date
ARG branch
ARG version
ARG patchlevel
ARG revision
ARG commitid
LABEL org.label-schema.name="simplicite" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-platform-$version-$branch" \
      org.opencontainers.image.title="Simplicite platform $version $branch" \
      org.opencontainers.image.description="Simplicite platform $version $branch" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.url="https://www.simplicite.io" \
      org.opencontainers.image.version="$version.$patchlevel.$revision" \
      org.opencontainers.image.revision="$commitid" \
      org.opencontainers.image.documentation="https://docs.simplicite.io" \
      org.opencontainers.image.licenses="https://docs.simplicite.io/license.md" \
      org.opencontainers.image.created="$date"

ARG template
COPY $template/tools/convert-mssql.sh /usr/local/bin
COPY $template/tools/convert-oracle.sh /usr/local/bin
COPY $template/app /usr/local/tomcat/webapps/ROOT
