FROM simplicite/server:centos8-base

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-centos8-openjdk-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-openjdk-${jvm}" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / OpenJDK = ${jvm}" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / OpenJDK = ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="${date}"

COPY jdk-${jvm} /usr/local/jdk
ENV JAVA_HOME=/usr/local/jdk

EXPOSE 8000
