FROM almalinux:latest

ARG date

LABEL org.label-schema.name="simplicite-server-almalinux" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-almalinux" \
      org.opencontainers.image.title="Simplicite server / AlmaLinux" \
      org.opencontainers.image.description="Simplicite server / AlmaLinux" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=almalinux LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JAVA_HOME=/usr/lib/jvm/java LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN dnf upgrade -y && \
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf -qy module disable postgresql && \
    dnf install -y bash openssh-clients openssl hostname bind-utils git curl wget zip unzip xz ca-certificates libjpeg fontconfig java-17-openjdk-devel mariadb postgresql14 && \
    dnf clean all && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    /bin/update-ca-trust extract && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite && \
    echo -e "alias dir='ls -alF --color=always'\n\
alias _mysql='mysql --host=$DB_HOST --port=$DB_PORT --user=$DB_USER --password=$DB_PASSWORD $DB_NAME'\n\
alias _psql='PGPASSWD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME'" >> /root/.bashrc

COPY --chown=simplicite:simplicite tomcat /usr/local/tomcat
COPY --chown=simplicite:simplicite run-tomcat.sh /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
