FROM FROM ghcr.io/graalvm/graalvm-ce:latest

ARG date

LABEL org.label-schema.name="simplicite-server-graalvm-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-graalvm" \
      org.opencontainers.image.title="Simplicite server / GraalVM" \
      org.opencontainers.image.description="Simplicite server / GraalVM" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=graalvm

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
RUN chmod +x /usr/local/tomcat/run && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
