ARG reg=registry.simplicite.io
FROM ${reg}/server:almalinux8-17

ARG date

LABEL org.label-schema.name="simplicite-server-devel" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-devel" \
      org.opencontainers.image.title="Simplicite server (devel)" \
      org.opencontainers.image.description="Simplicite server (devel)" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ARG ANT_VERSION=1.10.14
ARG MAVEN_VERSION=3.9.5
ARG GRADLE_VERSION=8.4
ARG NODE_VERSION=v18.18.2

RUN dnf install -y vim-enhanced gcc gcc-c++ make python3 python3-pyyaml iproute nmap xz procps && dnf clean all && \
    /usr/sbin/alternatives --set python /usr/bin/python3 && \
    cd /usr/local && \
    echo "Installing Apache Ant $ANT_VERSION" && \
    wget -qO- https://www-eu.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.tar.gz | tar xfz - && ln -s apache-ant-$ANT_VERSION ant && \
    echo "Installing Apache Maven $MAVEN_VERSION" && \
    wget -qO- https://www-eu.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xfz - && ln -s apache-maven-$MAVEN_VERSION maven && \
    echo "Installing Gradle $GRADLE_VERSION" && \
    wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip && unzip -q gradle-$GRADLE_VERSION-bin.zip && rm -f gradle-$GRADLE_VERSION-bin.zip && ln -s gradle-$GRADLE_VERSION gradle && \
    echo "Installing Node.js $NODE_VERSION" && \
    wget -qO- https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.xz | tar xfJ - && mv node-$NODE_VERSION-linux-x64 node-$NODE_VERSION && chown -R root:root node-$NODE_VERSION && ln -s node-$NODE_VERSION node &&\
    echo -e 'alias vi=vim' >> /root/.bashrc && \
echo -e '#!/bin/bash\n\
[ "$1" = "" ] && IN=/dev/stdin || IN=$1\n\
python3 -c "import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=2)" < $IN\n\
exit $?' > /usr/local/bin/yaml2json && chmod +x /usr/local/bin/yaml2json 

ENV ANT_HOME=/usr/local/ant \
    MAVEN_HOME=/usr/local/maven \
    GRADLE_HOME=/usr/local/gradle \
    JACOCO_HOME=/usr/local/jacoco \
    NODE_HOME=/usr/local/node \
    PATH=/usr/local/ant/bin:/usr/local/maven/bin:/usr/local/gradle/bin:/usr/local/node/bin:$PATH
