FROM adoptopenjdk:15-hotspot

ARG date
LABEL org.label-schema.name="simplicite-server-adoptopenjdk-hotspot" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-adoptopenjdk-hotspot" \
      org.opencontainers.image.title="Simplicite server / AdoptOpenJDK (hotspot)" \
      org.opencontainers.image.description="Simplicite server / AdoptOpenJDK (hotspot)" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"

RUN apt-get update && \
    apt-get upgrade -y&& \
    apt-get install -y bash git curl wget zip unzip ca-certificates libjpeg-dev uni2ascii mysql-client postgresql-client && \
    apt-get clean
ENV LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8
# JAVA_HOME is defined by default

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates && \
    chmod +x /usr/local/tomcat/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh

WORKDIR /usr/local/tomcat

EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/tomcat/run" ]
