ARG reg=registry.simplicite.io
ARG tag=6-latest
FROM $reg/platform:$tag

ARG maven=3.9.7
ARG deps
RUN wget -qO- https://www-eu.apache.org/dist/maven/maven-3/$maven/binaries/apache-maven-$maven-bin.tar.gz | tar xfz - && \
    MAVEN_HOME=/usr/local/tomcat/apache-maven-$maven ./adddeps.sh $deps && \
    rm -fr /usr/local/tomcat/apache-maven-$maven
