ARG reg=registry.simplicite.io
ARG tag=5-latest
ARG deps

FROM $reg/platform:$tag

USER simplicite
ARG MAVEN_VERSION=3.8.5
RUN wget -qO- https://www-eu.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xfz - && \
    MAVEN_HOME=/usr/local/tomcat/apache-maven-$MAVEN_VERSION ./adddeps.sh $deps && \
    rm -fr /usr/local/apache-maven-$MAVEN_VERSION
USER root
