ARG date
ARG jvm=latest

FROM simplicite/server:centos-base

LABEL org.label-schema.name="simplicite-server-centos7-temurin-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos7-temurin-${jvm}" \
      org.opencontainers.image.title="Simplicite server / CentOS 7 / Temurin OpenJDK ${jvm}" \
      org.opencontainers.image.description="Simplicite server / CentOS 7 / Temurin OpenJDK ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="${date}"

COPY jdk-${jvm} /usr/local/jdk
ENV JAVA_HOME=/usr/local/jdk

EXPOSE 8000
