ARG reg=registry.simplicite.io
FROM ${reg}/server:almalinux9-base

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-almalinux9-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-almalinux9-${jvm}" \
      org.opencontainers.image.title="Simplicite server / Almalinux 9 / Adoptium OpenJDK ${jvm}" \
      org.opencontainers.image.description="Simplicite server / Almalinux 9 / Adoptium OpenJDK ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ADD jdk-${jvm} /usr/local/jvm

ENV JAVA_HOME=/usr/local/jvm
RUN echo "JAVA_HOME=/usr/local/jvm
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH" > /etc/profile.d/java.sh

# JPDA, JaCoCo
EXPOSE 8000 8001

USER simplicite
