ARG reg=registry.simplicite.io
ARG tag=5-latest
FROM $reg/platform:$tag

# Install the SQLServer client 
ENV ACCEPT_EULA=Y
ADD https://packages.microsoft.com/config/rhel/7/prod.repo /etc/yum.repos.d/msprod.repo
RUN dnf install -y mssql-tools unixODBC-devel && dnf clean all
ENV PATH="/opt/mssql-tools/bin:${PATH}"

# Install the SQLServer JDBC driver
ADD https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/9.2.1.jre11/mssql-jdbc-9.2.1.jre11.jar /tmp
RUN rm -f /usr/local/tomcat/lib/mssql* && \
    cp /tmp/mssql-jdbc-9.2.1.jre11.jar /usr/local/tomcat/lib && \
    chmod go+r /usr/local/tomcat/lib/mssql-jdbc-9.2.1.jre11.jar && \
    rm -f /tmp/mssql-jdbc-9.2.1.jre11.jar
