FROM rockylinux/rockylinux:latest

ARG date

LABEL org.label-schema.name="simplicite-server-rockylinux" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-rockylinux" \
      org.opencontainers.image.title="Simplicite server / RockyLinux" \
      org.opencontainers.image.description="Simplicite server / RockyLinux" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=rockylinux LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JAVA_HOME=/usr/lib/jvm/java LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN dnf upgrade -y && \
    dnf install -y bash openssh-clients openssl hostname bind-utils git curl wget zip unzip ca-certificates libjpeg fontconfig java-17-openjdk-devel mariadb postgresql && \
    dnf clean all && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    /bin/update-ca-trust extract && \
    chmod +x /usr/local/tomcat/run && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
