FROM openjdk:alpine
MAINTAINER Simplicite.io <contact@simplicite.io>
RUN apk update && apk upgrade
RUN apk add --update bash ca-certificates mysql-client postgresql-client
RUN rm -rf /var/cache/apk/*
# JAVA_HOME is defined by default
COPY tomcat /usr/local/tomcat
RUN sed -i '/${tomcat.ajpport}/s/<!-- /</;/${tomcat.ajpport}/s/ -->/>/' /usr/local/tomcat/conf/server.xml
RUN chmod +x /usr/local/tomcat/bin/*.sh /usr/local/tomcat/run.sh
COPY /etc/pki/ca-trust/source/anchors/*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
EXPOSE 8005 8080 8443 8009 8000 8500
CMD cd /usr/local/tomcat; ./run.sh -t
