ARG tag=5-latest
FROM simplicite/platform:$tag

# Install the Oracle client 
ADD https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm /tmp
ADD https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-sqlplus-21.1.0.0.0-1.x86_64.rpm /tmp
RUN yum install -y libaio && yum clean all && \
    rpm -i /tmp/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm /tmp/oracle-instantclient-sqlplus-21.1.0.0.0-1.x86_64.rpm && \
    rm -f /tmp/*.rpm
