ARG reg=registry.simplicite.io
ARG tag=6-latest
#ARG tag=7-alpha
FROM ${reg}/platform:${tag}

USER root

#---------------------------------------------------------------------------------------------------------------------------------
# Install the SQLServer client
#---------------------------------------------------------------------------------------------------------------------------------
# For v6 use the RHEL 9 repository
ADD https://packages.microsoft.com/config/rhel/9/prod.repo /etc/yum.repos.d/msprod.repo
# For v7 use RHEL 10 repository
#ADD https://packages.microsoft.com/config/rhel/10/prod.repo /etc/yum.repos.d/msprod.repo
ENV ACCEPT_EULA=Y
RUN dnf install -y mssql-tools unixODBC-devel && dnf clean all
ENV PATH="/opt/mssql-tools/bin:${PATH}"

#---------------------------------------------------------------------------------------------------------------------------------
# Install the SQLServer JDBC driver
#---------------------------------------------------------------------------------------------------------------------------------
ADD https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/13.4.0.jre11/mssql-jdbc-13.4.0.jre11.jar /tmp
RUN rm -f /usr/local/tomcat/lib/mssql* && \
    cp /tmp/mssql-jdbc-13.4.0.jre11.jar /usr/local/tomcat/lib && \
    chmod go+r /usr/local/tomcat/lib/mssql-jdbc-13.4.0.jre11.jar && \
    rm -f /tmp/mssql-jdbc-13.4.0.jre11.jar && \
    echo "alias _sqlcmd='/opt/mssql-tools/bin/sqlcmd -S \$DB_HOST,\${DB_PORT:-1433} -U \$DB_USER -P \$DB_PASSWORD -d \$DB_NAME'" >> /etc/profile.d/simplicite.sh

USER simplicite
