FROM alpine:latest

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-alpine-temurin-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-alpine-temurin-${jvm}" \
      org.opencontainers.image.title="Simplicite server / Alpine / Temurin OpenJDK ${jvm}" \
      org.opencontainers.image.description="Simplicite server / Alpine / Temurin OpenJDK ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="$date"

ENV DOCKER=alpine LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8 JAVA_HOME=/usr/local/jvm LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY jdk-${jvm}-alpine /usr/local/jvm
COPY *.crt /usr/local/share/ca-certificates/
RUN apk update && apk upgrade && \
    apk add --update bash openssh-client openssl git curl wget zip unzip ca-certificates libjpeg fontconfig ttf-dejavu mysql-client postgresql-client && \
    rm -rf /var/cache/apk/* && \
    ln -s /usr/local/tomcat/logs /var/log/tomcat && \
    ln -s /usr/local/tomcat/webapps/ROOT/WEB-INF/log /var/log/simplicite && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    update-ca-certificates && \
    addgroup -g 2000 simplicite && adduser -D -G simplicite -u 2000 simplicite && \
    echo -e "alias rm='rm -i'\n\
alias cp='cp -i'\n\
alias mv='mv -i'\n\
alias dir='ls -alF --color=always'\n\
alias _mysql='mysql --host=\$DB_HOST --port=\${DB_PORT:-3306} --user=\$DB_USER --password=\$DB_PASSWORD \$DB_NAME'\n\
alias _psql='PGPASSWD=\$DB_PASSWORD psql -h \$DB_HOST -p \${DB_PORT:-5432} -U \$DB_USER \$DB_NAME'" > /etc/profile.d/simplicite.sh

COPY --chown=simplicite:simplicite tomcat /usr/local/tomcat
COPY --chown=simplicite:simplicite run-tomcat.sh /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
