FROM rockylinux:9

ARG date

LABEL org.label-schema.name="simplicite-server-rockylinux" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-rockylinux" \
      org.opencontainers.image.title="Simplicite server / RockyLinux" \
      org.opencontainers.image.description="Simplicite server / RockyLinux" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=rockylinux LANG=C.UTF-8 LANGUAGE=C.UTF-8 JAVA_HOME=/usr/lib/jvm/java LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN dnf upgrade -y && \
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf install -y --allowerasing bash openssh-clients openssl hostname bind-utils git curl wget zip unzip xz ca-certificates libjpeg fontconfig java-17-openjdk-devel mariadb postgresql15 && \
    dnf clean all && \
    /bin/update-ca-trust extract && \
    ln -s /usr/local/tomcat/logs /var/log/tomcat && \
    ln -s /usr/local/tomcat/webapps/ROOT/WEB-INF/log /var/log/simplicite && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite && \
    mkdir ~simplicite/.ssh && chmod 700 ~simplicite/.ssh && chown simplicite:simplicite ~simplicite/.ssh && \
    echo -e "alias dir='ls -alF --color=always'\n\
alias _mysql='mysql --host=\$DB_HOST --port=\${DB_PORT:-3306} --user=\$DB_USER --password=\$DB_PASSWORD \$DB_NAME'\n\
alias _psql='PGPASSWD=\$DB_PASSWORD psql -h \$DB_HOST -p \${DB_PORT:-5432} -U \$DB_USER \$DB_NAME'" > /etc/profile.d/simplicite.sh

COPY --chown=simplicite:simplicite tomcat /usr/local/tomcat
COPY --chown=simplicite:simplicite run-tomcat.sh /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
