FROM centos:8
LABEL org.label-schema.name="simplicite" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.url="https://www.simplicite.io" \
      org.label-schema.description="Simplicite server (centos)"
# ZZZ Temporary (epel latest JDK is not working)
#RUN yum upgrade -y && yum clean all && yum install -y epel-release && yum -y install bash git curl ca-certificates libjpeg java-latest-openjdk-devel mariadb postgresql && yum clean all && rm -rf /var/cache/yum
RUN yum upgrade -y && yum clean all && yum install -y bash git curl ca-certificates libjpeg java-11-openjdk-devel mariadb postgresql && yum clean all && rm -rf /var/cache/yum
ENV LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JAVA_HOME=/usr/lib/jvm/java
COPY run.sh /usr/local/bin/run
COPY tomcat /usr/local/tomcat
RUN chmod +x /usr/local/bin/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract
EXPOSE 8080 8443 8444 8009 8005 8000
CMD /usr/local/bin/run
