FROM centos:8

ARG date
LABEL org.label-schema.name="simplicite-server-centos8-openjdk-$jvm" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-openjdk-$jvm" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / OpenJDK = $jvm" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / OpenJDK = $jvm" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"

ARG jvm=latest
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf install -y epel-release && \
    dnf install -y bash git curl wget ca-certificates libjpeg java-${jvm}-openjdk-devel mariadb postgresql && \
    dnf clean all && \
    rpm -i http://mirrors.ircam.fr/pub/dag/redhat/el7/en/x86_64/rpmforge/RPMS/uni2ascii-4.18-1.el7.rf.x86_64.rpm
ENV LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JAVA_HOME=/usr/lib/jvm/java
COPY run.sh /usr/local/bin/run
COPY tomcat /usr/local/tomcat
RUN chmod +x /usr/local/bin/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract

EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/bin/run" ]
