FROM openjdk:alpine
MAINTAINER Simplicite.io <contact@simplicite.io>
RUN apk add --update bash mysql-client postgresql-client && rm -rf /var/cache/apk/*
# JAVA_HOME is defined by default
COPY tomcat /usr/local/tomcat
RUN sed -i '/${tomcat.ajpport}/s/<!-- /</;/${tomcat.ajpport}/s/ -->/>/' /usr/local/tomcat/conf/server.xml
RUN chmod +x /usr/local/tomcat/bin/*.sh /usr/local/tomcat/run.sh
EXPOSE 8005 8080 8443 8009
CMD cd /usr/local/tomcat; ./run.sh -t
