# FROM centos:8
FROM quay.io/centos/centos:stream8

ARG date

LABEL org.label-schema.name="simplicite-server-centos8-base" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-centos8-base" \
      org.opencontainers.image.title="Simplicite server / CentOS 8 / Base" \
      org.opencontainers.image.description="Simplicite server / CentOS 8 / Base" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ENV DOCKER=centos8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LOG4J_FORMAT_MSG_NO_LOOKUPS=true

COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN dnf upgrade -y && \
    dnf install -y epel-release && \
    dnf install -y bash openssh-clients openssl hostname bind-utils git curl wget zip unzip xz ca-certificates libjpeg fontconfig mariadb postgresql && \
    dnf clean all && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    /bin/update-ca-trust extract && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite

COPY --chown=simplicite:simplicite tomcat /usr/local/tomcat
COPY --chown=simplicite:simplicite run.sh /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8555
CMD [ "/usr/local/tomcat/run" ]
