ARG reg=registry.simplicite.io
ARG ext
FROM ${reg}/server:almalinux10-base${ext}

ARG date
ARG jvm=latest

LABEL org.label-schema.name="simplicite-server-almalinux10-${jvm}" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.license="NONE" \
      org.label-schema.build-date="${date}" \
      org.opencontainers.image.ref.name="simplicite-server-almalinux10-${jvm}" \
      org.opencontainers.image.title="Simplicite server / Almalinux 10 / Adoptium OpenJDK ${jvm}" \
      org.opencontainers.image.description="Simplicite server / Almalinux 10 / Adoptium OpenJDK ${jvm}" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.licenses="NONE" \
      org.opencontainers.image.created="${date}"

ADD jdk-${jvm} /usr/local/jvm
ENV JAVA_HOME=/usr/local/jvm PATH=/usr/local/jvm/bin:$PATH

# JPDA, JaCoCo
EXPOSE 8000 8001

USER simplicite
