FROM centos:8

ARG GIT_VERSION=2.34.0
ARG ANT_VERSION=1.10.12
ARG MAVEN_VERSION=3.8.4
ARG GRADLE_VERSION=7.3

USER root
RUN dnf upgrade -y && \
    dnf install -y epel-release && \
    dnf install -y bash vim-enhanced pkgconf autoconf gcc gcc-c++ make zlib-devel libcurl-devel libsecret-devel nmap openssh-clients openssl curl wget zip unzip ca-certificates libjpeg fontconfig mariadb postgresql java-11-openjdk-devel && \
    dnf clean all && \
    cd /usr/local && \
    echo "Installing Git $GIT_VERSION" && \
    wget -qO- https://mirrors.edge.kernel.org/pub/software/scm/git/git-$GIT_VERSION.tar.xz | tar xfJ - && \
    cd git-$GIT_VERSION && make configure && ./configure --prefix=/usr/local && make install && cd .. && rm -fr git-$GIT_VERSION && \
    echo "Installing Apache Ant $ANT_VERSION" && \
    wget -qO- https://www-eu.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.tar.gz | tar xfz - && \
    echo "Installing Apache Maven $MAVEN_VERSION" && \
    wget -qO- https://www-eu.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xfz - && \
    echo "Installing Gradle $GRADLE_VERSION" && \
    wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip && unzip -q gradle-$GRADLE_VERSION-bin.zip && rm -f gradle-$GRADLE_VERSION-bin.zip && \
    groupadd -g 1000 simplicite && useradd -N -g 1000 -u 1000 -d /var/simplicite simplicite

ENV LANG=en_US.UTF-8 \
    ANT_HOME=/usr/local/apache-ant-$ANT_VERSION \
    MAVEN_HOME=/usr/local/apache-maven-$MAVEN_VERSION \
    GRADLE_HOME=/usr/local/gradle-$GRADLE_VERSION \
    NODE_HOME=/usr/local/node-$NODE_VERSION-linux-x64 \
    PATH=/usr/local/bin:/usr/local/apache-ant-$ANT_VERSION/bin:/usr/local/apache-maven-$MAVEN_VERSION/bin:/usr/local/gradle-$GRADLE_VERSION/bin:$PATH

USER simplicite
RUN git config --global user.name "Simplicite Software" && \
    git config --global user.email "contact@simplicitesoftware.com" && \
    git config --global http.sslVerify "false" && \
    mkdir /var/simplicite/projects && \
    echo -e "alias vi=vim\n\
alias rm='rm -i'\n\
alias cp='cp -i'\n\
alias mv='mv -i'\n\
alias dir='ls -alF --color=always'" >> /var/simplicite/.bashrc

USER root
