FROM centos:7
ARG date
LABEL org.label-schema.name="simplicite" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server" \
      org.opencontainers.image.title="Simplicite server" \
      org.opencontainers.image.description="Simplicite server" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"
RUN yum upgrade -y && \
    yum clean all && \
    yum install -y epel-release && \
    yum install -y yum-utils bash git curl wget ca-certificates libjpeg mariadb postgresql && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    package-cleanup --oldkernels --count=1 && \
    rpm -i http://mirrors.ircam.fr/pub/dag/redhat/el7/en/x86_64/rpmforge/RPMS/uni2ascii-4.18-1.el7.rf.x86_64.rpm && \
    wget -qO- https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz | tar xfz - -C /opt
ENV JAVA_HOME=/opt/jdk-15 PATH=/opt/jdk-15/bin/:$PATH LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8
COPY run.sh /usr/local/bin/run
COPY tomcat /usr/local/tomcat
RUN chmod +x /usr/local/bin/run /usr/local/tomcat/*.sh /usr/local/tomcat/bin/*.sh
COPY *.crt /etc/pki/ca-trust/source/anchors/
RUN /bin/update-ca-trust extract
EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/bin/run" ]
