ARG jvm
FROM openjdk:${jvm}-slim

ARG date
LABEL org.label-schema.name="simplicite-server-openjdk-${jvm}-slim" \
      org.label-schema.vendor="Simplicite Software" \
      org.label-schema.build-date="$date" \
      org.opencontainers.image.ref.name="simplicite-server-openjdk-${jvm}-slim" \
      org.opencontainers.image.title="Simplicite server / OpenJDK ${jvm} slim" \
      org.opencontainers.image.description="Simplicite server / OpenJDK ${jvm} slim" \
      org.opencontainers.image.vendor="Simplicite Software" \
      org.opencontainers.image.created="$date"

ENV DOCKER=openjdk-slim LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8

COPY tomcat /usr/local/tomcat
COPY run.sh /usr/local/tomcat/run
COPY *.crt /usr/local/share/ca-certificates/
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y apt-utils && \
    apt-get install -y bash openssh-client git curl wget zip unzip ca-certificates libjpeg-dev mariadb-client postgresql-client && \
    apt-get clean && \
    mkdir /root/.ssh && chmod 700 /root/.ssh && \
    update-ca-certificates && \
    chmod +x /usr/local/tomcat/run

WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8444 8009 8005 8000 8555
CMD [ "/usr/local/tomcat/run" ]
