---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplicite-git-volume-claim
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
