---
apiVersion: v1
kind: Service
metadata:
  name: simplicite
  labels:
    app: simplicite
spec:
  selector:
    app: simplicite
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
status:
  loadBalancer: {}
