FROM almalinux:10

ARG java=25
ARG tomcat=9.0.x
ARG simplicite=6.3.y

WORKDIR /home/simplicite

ADD https://dlcdn.apache.org/tomcat/tomcat-9/v${tomcat}/bin/apache-tomcat-${tomcat}.tar.gz /tmp/
ADD simplicite-${simplicite}.war /tmp/
RUN dnf upgrade -y && dnf install -y unzip java-${java}-openjdk && dnf clean all && \
    groupadd -g 2000 simplicite && useradd -N -g 2000 -u 2000 simplicite && \
    tar xfz /tmp/apache-tomcat-${tomcat}.tar.gz -C /home/simplicite/ && rm -f /tmp/apache-tomcat-${tomcat}.tar.gz && \
    mv /home/simplicite/apache-tomcat-${tomcat} /home/simplicite/tomcat && rm -fr /home/simplicite/tomcat/webapps/* && \
    unzip /tmp/simplicite-${simplicite}.war -d /home/simplicite/tomcat/webapps/ROOT && rm -f /tmp/simplicite-${simplicite}.war && \
    chown -R simplicite: /home/simplicite

USER simplicite

EXPOSE 8080
CMD [ "/home/simplicite/tomcat/bin/catalina.sh", "run" ]
