---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    name: mysql-volume
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
