services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Simplicite Software registry"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/users.pwd"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - /mnt/data/auth:/auth
      - /mnt/data/registry:/var/lib/registry
  registry-ui:
    image: klausmeyer/docker-registry-browser
    restart: always
    container_name: registry-ui
    environment:
       SECRET_KEY_BASE: "changeme"
       DOCKER_REGISTRY_URL: "http://registry:5000"
    ports:
      - 127.0.0.1:5001:8080
  registry-pt:
    image: "portainer/portainer-ce:latest"
    container_name: registry-pt
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 127.0.0.1:9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
