version: "3"
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Simplicite Software registry"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/users.pwd"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - /mnt/registry/auth:/auth
      - /mnt/registry/data:/var/lib/registry
