version: "3"
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Simplicite Software registry"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/users.pwd"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - /mnt/registry/auth:/auth
      - /mnt/registry/data:/var/lib/registry
  registry-ui:
    image: parabuzzle/craneoperator:latest
    restart: always
    container_name: registry-ui
    environment:
      REGISTRY_HOST: "registry"
      REGISTRY_PORT: "5000"
      REGISTRY_PROTOCOL: "http"
      REGISTRY_ALLOW_DELETE: "false"
      ALLOW_REGISTRY_LOGIN: "true"
      REGISTRY_PUBLIC_URL: "https://registry.simplicite.io"
      TITLE: "Simplicite Docker registry"
    ports:
      - 127.0.0.1:5001:80
