# See the README.md file for instructions to build this "FROM" image
FROM oracle/database:21.3.0-xe
ENV ORACLE_CHARACTERSET=AL32UTF8 ORACLE_PWD=_Str0ng_Passw0rd_
ADD init.sql /opt/oracle/scripts/setup
