---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplicite-git-volume
  labels:
    type: local
    app: simplicite
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/git"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplicite-git-claim
  labels:
    app: simplicite
spec:
  volumeName: simplicite-git-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simplicite
  name: simplicite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simplicite
        date: "2019-05-22"
    spec:
      containers:
        - name: simplicite
          image: <simplicite|registry.simplicite.io>/platform:<tag, e.g. 5-latest>
          imagePullPolicy: Always
          ports:
            # if exposed in http://
            - containerPort: 8080
            # if exposed in https:// (ZZZ never use 8080 when expos*ed* in https:// ZZZ) 
            #- containerPort: 8443
            # if exposing in https:// (ZZZ never use 8080/8443 if expos*ing* in https:// ZZZ, a custom image with appropriate JKS certificate is required in this mode) 
            #- containerPort: 8444
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: simplicite
            - name: DB_PASSWORD
              value: simplicite
            - name: DB_SETUP
              value: "true"
            - name: DB_USER
              value: simplicite
            - name: DB_VENDOR
              value: postgresql
            - name: DB_WAIT
              value: "100"
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/git
              name: simplicite-git
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: simplicite-git
          persistentVolumeClaim:
            claimName: simplicite-git-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simplicite
  name: simplicite
spec:
  type: LoadBalancer
  ports:
    # ZZZ to be adapted if you are not using 8080 ZZZ
    - port: 80
      targetPort: 8080
  selector:
    app: simplicite
status:
  loadBalancer: {}
