---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplicite-git-volume
  labels:
    type: local
    app: simplicite
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/git"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplicite-git-claim
  labels:
    app: simplicite
spec:
  volumeName: simplicite-git-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplicite
  labels:
    app: simplicite
spec:
  # ZZZ more than 1 replica **requires** sticky session load balancing ZZZ
  replicas: 1
  selector:
    matchLabels:
      app: simplicite
  template:
    metadata:
      labels:
        app: simplicite
    spec:
      containers:
        - name: simplicite
          image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
          ports:
            # if exposed in http://
            - containerPort: 8080
            # if exposed in https:// (ZZZ never use 8080 when expos*ed* in https:// ZZZ) 
            #- containerPort: 8443
            # if exposing in https:// (ZZZ never use 8080/8443 if expos*ing* in https:// ZZZ, a custom image with appropriate JKS certificate is required in this mode) 
            #- containerPort: 8444
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: simplicite
            - name: DB_PASSWORD
              value: simplicite
            - name: DB_SETUP
              value: "true"
            - name: DB_USER
              value: simplicite
            - name: DB_VENDOR
              value: postgresql
            - name: DB_WAIT
              value: "100"
            # Useful in case of multiple replicas to allow each instance to communicate with the others over the I/O endpoint (e.g. to propagate a clear cache)
            #- name: IO_PASSWORD
            #  value: "<a very strog password>"
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/git
              name: simplicite-git
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: simplicite-git
          persistentVolumeClaim:
            claimName: simplicite-git-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simplicite
  name: simplicite
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    # ZZZ to be adapted if you are not using 8080 ZZZ
    - port: 8080
      targetPort: 8080
  selector:
    app: simplicite
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: simplicite
            port:
              # ZZZ to be adapted if you are not using 8080 ZZZ
              number: 8080
        path: /
        pathType: Prefix