---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  labels:
    name: postgresql-volume
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgresql-disk
    fsType: ext4
