---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume-claim
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: postgresql-volume
