version: "3"
services:
  nginx: 
    image: nginx:latest
    restart: always
    container_name: myrp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/ssl/server.crt
      - ./server.key:/etc/ssl/server.key
  simplicite:
    image: <simplicite|registry.simplicite.io>/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp
    volumes:
      - myapp_db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - myapp_dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - myapp_git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
volumes:
  myapp_db:
  myapp_dbdoc:
  myapp_git:
