version: "3"
services:
  simplicite:
    image: simplicite/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp
    ports:
      - 81:8080
      - 444:8444
    environment:
      SSL: "true"
      KEYSTORE_FILE: "/usr/local/tomcat/cert/manager.simplicite.io.jks"
      KEYSTORE_PASSWORD: "password"
    volumes:
      - myapp_db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - myapp_dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - myapp_git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
      - /etc/ssl:/usr/local/tomcat/cert:ro
volumes:
  myapp_db:
  myapp_dbdoc:
  myapp_git:
