version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: myapp-postgresql-database
    environment:
      POSTGRES_USER: "simplicite"
      POSTGRES_PASSWORD: "simplicite"
      POSTGRES_DB: "simplicite"
    # Uncomment if you need to access the database from the host
    #ports:
    #  - 127.0.0.1:5432:5432
    volumes:
      - myapp-postgresql-db:/var/lib/postgresql/data
  simplicite:
    image: <simplicite|registry.simplicite.io>/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp-postgresql-webapp
    environment:
      DB_SETUP: "true"
      DB_VENDOR: "postgresql"
      DB_HOST: db
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - myapp-postgresql-git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - db
volumes:
  myapp-postgresql-db:
  myapp-postgresql-git:
