version: "3"
services:
  simplicite:
    image: simplicite/platform:5-alpha
    restart: always
    container_name: myapp
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
    volumes:
      - myapp_db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - myapp_dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - myapp_git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
volumes:
  myapp_db:
  myapp_dbdoc:
  myapp_git:
