services:
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
    restart: always
    container_name: simplicite
    ports:
      - 80:8080
      - 443:8444
    environment:
      SSL: "true"
      KEYSTORE_FILE: "/usr/local/tomcat/cert/manager.simplicite.io.jks"
      KEYSTORE_PASSWORD: "password"
    volumes:
      - db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
      - /etc/ssl:/usr/local/tomcat/cert:ro
volumes:
  db:
  dbdoc:
  git:
