version: "3"
services:
  simplicite:
    image: <simplicite|registry.simplicite.io>/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp
    environment:
      IO_PASSWORD: "<a very strong password dedicated to I/O access (only if needed)>"
      DB_SETUP: "true"
      DB_VENDOR: "<database vendor: hsqldb, mysql, postgresql, oracle or msssql>"
      # The following variables are *not* required with embedded HSQLDB
      DB_HOST: "<database host>"
      DB_PORT: "<database port>"
      DB_USER: "<database user>"
      DB_PASSWORD: "<database password>"
      DB_NAME: "<database name>"
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "<Max CPU share, e.g. 2>"
          memory: "<Max memory, e.g. 2G>"
    read_only: true
    tmpfs:
      # System temp dir
      - /tmp
      # Tomcat work dirs
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/work
      - /usr/local/tomcat/conf/Catalina
      # Tomcat log dir, may be mounted as a persistent volume if needed
      - /usr/local/tomcat/logs
      # Simplicite work dirs
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/tmp
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/recyclebin
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/cache
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/src
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/bin
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/build
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/jar
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/maven
      # Simplicite log dir, may be mounted as a persistent volume if needed
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/log
      # The following directories may be mounted as persistent volumes if needed
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/content
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/doc
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/import
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/export
      - /usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/index
    volumes:
      # For embedded HSQLDB *only*
      #- myapp_db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      # For embedded HSQLDB or non-BLOB deployments *only*
      #- myapp_dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - myapp_git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
volumes:
  # For embedded HSQLDB *only*
  #myapp_db:
  # For embedded HSQLDB or non-BLOB deployments *only*
  #myapp_dbdoc:
  myapp_git:
