version: "3"
services:
  cache:
    image: redis:latest
    restart: always
    container_name: cache
    # Uncomment if you need to access the cache from the host
    #ports:
    #  - 127.0.0.1:6379:6379
  simplicite:
    image: simplicite/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - myapp_db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - myapp_dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - myapp_git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - cache
volumes:
  myapp_db:
  myapp_dbdoc:
  myapp_git:
