services:
  database:
    image: mysql:latest
    restart: unless-stopped
    container_name: database
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      # Custom timezone if needed ZZZ must match the simplicite container timezone ZZZ
      #TZ: "Europe/Paris"
      MYSQL_ROOT_PASSWORD: "simplicite"
      MYSQL_DATABASE: "simplicite"
      MYSQL_USER: "simplicite"
      MYSQL_PASSWORD: "simplicite"
    # Uncomment if you need to access the database from the host
    #ports:
    #  - 127.0.0.1:3306:3306
    volumes:
      - data:/var/lib/mysql
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
    restart: unless-stopped
    container_name: simplicite
    environment:
      # Custom timezone if needed ZZZ must match the database container timezone ZZZ
      #TOMCAT_TIMEZONE: "Europe/Paris"
      DB_SETUP: "true"
      DB_VENDOR: "mysql"
      DB_HOST: "database"
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - database
volumes:
  data:
  git:
