services:
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
    restart: unless-stopped
    container_name: simplicite
    environment:
      DB_SETUP: "true"
      DB_VENDOR: "<mysql|postgresql|mssql|oracle>"
      DB_HOST: "<your database server hostname or IP address>"
      DB_PORT: "<your database server hostname or IP address>"
      DB_USER: "<your database username>"
      DB_PASSWORD: "<your database password>"
      DB_NAME: "<your database name>"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
volumes:
  git: