services:
  database:
    # See ../databases/oraclexe to build this custom Oracle image
    image: registry.simplicite.io/oracle:<version>
    restart: unless-stopped
    container_name: database
    #environment:
      # Custom timezone if needed ZZZ must match the simplicite container timezone ZZZ
      #TZ: "Europe/Paris"
    # Uncomment if you need to access the database from the host
    #ports:
    #  - 127.0.0.1:1521:1521
    volumes:
      - data:/opt/oracle/oradata
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>-with-oracle-client
    # Copy ../../Dockerfile-platform-oracle in this folder
    build:
      context: .
      dockerfile: Dockerfile-platform-oracle
      args:
        tag: <tag, e.g. 6-latest>
    restart: unless-stopped
    container_name: simplicite
    environment:
      # Custom timezone if needed ZZZ must match the database container timezone ZZZ
      #TOMCAT_TIMEZONE: "Europe/Paris"
      DB_SETUP: "true"
      DB_VENDOR: "oracle"
      DB_HOST: "database"
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "xe"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - database
volumes:
  data:
  git:
