version: "3"
services:
  nginx: 
    image: nginx:latest
    restart: always
    container_name: myrp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/ssl/server.crt
      - ./server.key:/etc/ssl/server.key
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: simplicite
    volumes:
      - db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
volumes:
  db:
  dbdoc:
  git:
