version: "3.8"
services:
  cache:
    image: redis:latest
    restart: always
    container_name: cache
    # Uncomment if you need to access the cache from the host
    #ports:
    #  - 127.0.0.1:6379:6379
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
    restart: always
    container_name: simplicite
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - cache
volumes:
  db:
  dbdoc:
  git:
