services:
  simplicite:
    image: registry.simplicite.io/platform:<tag, e.g. 6-latest>
    restart: always
    container_name: simplicite
    environment:
      # Uncomment these 3 lines if you are implementing a custom frontend
      #CORS: "true"
      #CORS_ORIGINS: "http://localhost:3000"
      #CORS_CREDENTIALS: "true"
      JPDA: "true"
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
      - 8000:8000
    volumes:
      - db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
      - git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
  vscode:
    image: registry.simplicite.io/vscode:latest
    restart: always
    container_name: myide
    ports:
      - 127.0.0.1:3030:3030
      # Uncomment this line if you are implementing a custom frontend
      #- 127.0.0.1:3000:3000
    volumes:
      - projects:/var/simplicite/projects
      # Uncomment if you want custom extensions
      #- extensions:/var/simplicite/extensions
      # Uncomment to keep user prefs, etc.
      #- data:/var/simplicite/data
volumes:
  db:
  dbdoc:
  git:
  projects:
  #extensions:
  #data:
