version: "3"
services:
  db:
    # See ../databases/mssql to build this cutom image
    image: mymssql 
    restart: always
    container_name: myapp-mssql-database
    volumes:
      - myapp-mssql:/var/opt/mssql
  simplicite:
    build:
      context: .
      dockerfile: Dockerfile-platform-mssql
      args:
        tag: <tag, e.g. 5-latest>
    restart: always
    container_name: myapp-mssql-webapp
    environment:
      DB_SETUP: "true"
      DB_VENDOR: "mssql"
      DB_HOST: db
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - myapp-mssql-git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - db
volumes:
  myapp-mssql-db:
  myapp-mssql-git:
