version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: myapp-mysql-database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "simplicite"
      MYSQL_DATABASE: "simplicite"
      MYSQL_USER: "simplicite"
      MYSQL_PASSWORD: "simplicite"
    # Uncomment if you need to access the database from the host
    #ports:
    #  - 127.0.0.1:3306:3306
    volumes:
      - myapp-mysql-db:/var/lib/mysql
  simplicite:
    image: <simplicite|registry.simplicite.io>/platform:<tag, e.g. 5-latest>
    restart: always
    container_name: myapp-mysql-webapp
    environment:
      DB_SETUP: "true"
      DB_VENDOR: "mysql"
      DB_HOST: db
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
    ports:
      # For *non* SSL endoint of HTTP reverse proxying
      - 127.0.0.1:8080:8080
      # For SSL endpoint of HTTP reverse proxying
      - 127.0.0.1:8443:8443
      # For AJP reverse proxying
      - 127.0.0.1:8009:8009
    volumes:
      - myapp-mysql-git:/usr/local/tomcat/webapps/ROOT/WEB-INF/git
    depends_on:
      - db
volumes:
  myapp-mysql-db:
  myapp-mysql-git:
